# For tests only
testMode=false

# Populate database with fake demo data
demoData=false

# Use SSL/TLS with the given cert and key files
useSSL=false
sslCertPath="/path/to/cert"
sslKeyPath="/path/to/key"

# Where Graviton listens
serverAddress=":10000"

# Where to redirect after an authentication
redirectAddress = "http://localhost:8080/#/authenticated"

# Address for MongoDB
mongoAddress="localhost"

# MongoDB database name
dbName="graviton"

# CORS origins to allow
corsOrigins = ["http://localhost:8080"]

# Google auth information
googleClientId="your_id_here"
googleSecret="your_secret_here"

# Root for oauth redirects (external server address)
serverRedirect = "http://localhost:10000"