# For tests only
testMode=false

# Populate database with fake demo data
demoData=false

# Use echo AutoTLS (server address must be a domain which maps to your public IP)
useSSL=false

# Where to cache AutoTLS certs
sslCache = "/var/www/.cache"

# Where Graviton listens
serverAddress=":10000"

# Where to redirect after an authentication
redirectAddress = "http://localhost:8080/#/authenticated"

# Address for MongoDB
mongoAddress="localhost"

# MongoDB database name
dbName="graviton"

# CORS origins to allow
corsOrigins = ["http://localhost:8080"]

# Google auth information
googleClientId="your_id_here"
googleSecret="your_secret_here"